### ISSUE TITLE
The phone closes immediately

### ISSUE THREAD

**Issue by ahmetilhann** [Vizir/react-native-paypal#15]
The application is running smoothly on the simulator. But when I install it on the device, the application closes before it is turned on. 

react-native: 50.3v

MainActivity: https://gist.github.com/ahmetilhann/31bee87196927a1f050f9075fd3c3165
MaınApplıcatıon: https://gist.github.com/ahmetilhann/4db65054fbcea55c0f72190cc95d703f

**Comment by chagasaway** [comment]
hey @ahmetilhann, this library is not maintained anymore, please take a look on this repo: https://github.com/MattFoley/react-native-paypal - they provide a similar API and maybe this issue is solved there.
