### ISSUE TITLE
what is otherModulesHandlers(requestCode, resultCode, data)

### ISSUE THREAD

**Issue by jojonarte** [Vizir/react-native-paypal#9]
It is on   

`  @Override
   public void onActivityResult(final int requestCode, final int resultCode, final Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == PAY_PAL_REQUEST_ID) {
            payPalPackage.handleActivityResult(requestCode, resultCode, data); // <--
        } else {
            otherModulesHandlers(requestCode, resultCode, data); //<--

```
    }
 }`
```

I wonder what it does? It is not an available module.

**Comment by chagasaway** [comment]
Hey @jojonarte,

That _otherModulesHandlers_ is an example for other activity handlers that your app may have. For exemple, a Facebook Login activity handler, etc.

If do not have any activities to handle, just ignore this because you do not need it.

**Comment by jojonarte** [comment]
Oh thanks man now closing this.
